### ISSUE TITLE
Tab on empty line, esarea add indent to previous line of end

### ISSUE THREAD

**Issue by inabajunmr** [fukayatsu/esarea#22]
空行でタブを押すとインデントが前の行の末尾に追加されます。

インデント=◾️
カーソル=|
として以下の状態でタブを押すと、
```
aaaa
|
```
以下の形になります
```
aaaa◾️
|
```

esa.ioではカーソルのある行に直接インデントが追加され、こちらの挙動が自然と感じました。

**Comment by fukayatsu** [comment]
再現できました 🙇 後ほど修正します

**Comment by fukayatsu** [comment]
> アイテムは公開処理中です。Chrome ウェブストアに表示されるようになるまで最大 60 分かかることがあります。
